### ISSUE TITLE
Soxr is not Send but it could be

### ISSUE THREAD

**Issue by teodly** [lrbalt/libsoxr-rs#6]
I'm a beginner to Rust so I may be wrong.

According to [The Rustonomicon](https://doc.rust-lang.org/nomicon/send-and-sync.html),
> Something can safely be Send unless it shares mutable state with something else without enforcing exclusive access to it.

so adding that line to soxr.rs should suffice:

```rust
unsafe impl Send for Soxr {}
```

**Comment by lrbalt** [comment]
I remember reading somewhere that libsoxr is not thread safe. Therefore I did not add the ```impl Send```. Are you sure that libsoxr is thread safe?

**Comment by lrbalt** [comment]
"Unfortunately, libSoX uses some global state and is thus not completely thread-safe"

from https://public-inbox.org/sox-devel/000601ce9245$28e30b50$7aa921f0$@symonics.com/T/ 

Closing for this reason

**Comment by WilliamVenner** [comment]
Wouldn't that mean it could be Send but !Sync? So long as the underlying libSoX object/pointer is only accessed through a mutable reference.
